import { Inter } from "next/font/google";
import BottomNav from "@components/BottomNav";
import ReduxProvider from "@/src/redux/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Doctor Appointment App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>{children}</ReduxProvider>
        <BottomNav />
      </body>
    </html>
  );
}
